MODEL_NAME = "best_4"
OVERLAPPING_PERCENTAGE = 20
SLICE_SIZE = 640
SLICES_FOLDER = "slices-2"

PREDICT_FOLDER_PREFIX = "predicted_images_with_annotations"
CONFIDENCE_THRESHOLD = 0.5

OUTLIER_FILTER_FOLDER_PREFIX = "outlier_filtered"
OUTLIER_THRESHOLD_K = 3

IOU_FOLDER_PREFIX = "iou_filtered"
IOU_THRESHOLD = 0.5